version: "2"
checks:
  method-complexity:
    enabled: false
  method-lines:
    enabled: false
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-51

exclude_patterns:
  - '*.rb'
  - 'setup/**/*'
  - 'Vagrantfile'
  - 'docs/**/*'
  - 'hailstorm-gem/Gemfile'
  - 'hailstorm-gem/hailstorm.gemspec'
  - 'hailstorm-gem/Rakefile'
  - 'hailstorm-gem/bin/**/*'
  - 'hailstorm-gem/features/**/*'
  - 'hailstorm-gem/lib/hailstorm/java/**/*'
  - 'hailstorm-gem/spec/**/*'
  - 'hailstorm-gem/templates/**/*'
  - 'hailstorm-gem/tmp/**/*'
  - 'hailstorm-redis/**/*'
  - 'hailstorm-site/**/*'
  - 'hailstorm-web/**/*'
