version: "2"
checks:
  method-complexity:
    enabled: false
  method-lines:
    enabled: false
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-89

exclude_patterns:
  - 'docs/**/*'
  - 'hailstorm-gem/lib/hailstorm/java/**/*'
  - 'hailstorm-gem/spec/**/*'
  - 'hailstorm-cli/spec/**/*'
  - 'hailstorm-api/spec/**/*'
  - 'hailstorm-web-client/src/index.tsx'
  - 'hailstorm-web-client/src/serviceWorker.ts'
  - 'hailstorm-web-client/**/*.test.*'
  - 'hailstorm-web-client/e2e/features/step-definitions/*.steps.ts'
  - 'hailstorm-file-server/src/test/**/*Test.java'
  - 'hailstorm-client-exchange/src/test/**/*Test.java'
