version: "2"
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-51

exclude_patterns:
  - '*.rb'
  - 'Vagrantfile'
  - 'docs/**/*'
  - 'hailstorm-gem/Gemfile'
  - 'hailstorm-gem/hailstorm.gemspec'
  - 'hailstorm-gem/Rakefile'
  - 'hailstorm-gem/bin/**/*'
  - 'hailstorm-gem/features/**/*'
  - 'hailstorm-gem/spec/**/*'
  - 'hailstorm-gem/templates/**/*'
  - 'hailstorm-gem/tmp/**/*'
  - 'hailstorm-redis/**/*'
  - 'hailstorm-site/**/*'
  - 'hailstorm-web/**/*'

