# Top level rules
AllCops:
  Exclude:
    - '*.rb'
    - 'setup/**/*'
    - 'Vagrantfile'
    - 'docs/**/*'
    - 'hailstorm-gem/Gemfile'
    - 'hailstorm-gem/hailstorm.gemspec'
    - 'hailstorm-gem/Rakefile'
    - 'hailstorm-gem/features/**/*'
    - 'hailstorm-gem/spec/**/*'
    - 'hailstorm-gem/templates/**/*'
    - 'hailstorm-gem/build/**/*'
    - 'hailstorm-redis/**/*'
    - 'hailstorm-site/**/*'
    - 'hailstorm-web/**/*'
    - 'hailstorm-cli/Gemfile'
    - 'hailstorm-cli/hailstorm-cli.gemspec'
    - 'hailstorm-cli/Rakefile'
    - 'hailstorm-cli/bin/**/*'
    - 'hailstorm-cli/features/**/*'
    - 'hailstorm-cli/spec/**/*'
    - 'hailstorm-cli/templates/**/*'
    - 'hailstorm-cli/build/**/*'
    - 'hailstorm-api/spec/**/*'

Lint/RescueException:
  Enabled: false

Lint/InheritException:
  Enabled: false

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/Not:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 26

Metrics/MethodLength:
  Max: 25

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Performance/Caller:
  Enabled: false

Security/YAMLLoad:
  Enabled: false # safe_load is not as versatile as load

