# Top level rules
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'docs/**/*'
    - 'hailstorm-gem/build/**/*'
    - 'hailstorm-cli/build/**/*'

Lint/RescueException:
  Enabled: false

Lint/InheritException:
  Enabled: false

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Lint/BinaryOperatorWithIdenticalOperands: # (new in 0.89)
  Enabled: true

Lint/DeprecatedOpenSSLConstant: # (new in 0.84)
  Enabled: true

Lint/DuplicateElsifCondition: # (new in 0.88)
  Enabled: true

Lint/DuplicateRescueException: # (new in 0.89)
  Enabled: true

Lint/EmptyConditionalBody: # (new in 0.89)
  Enabled: true

Lint/FloatComparison: # (new in 0.89)
  Enabled: true

Lint/MissingSuper: # (new in 0.89)
  Enabled: true

Lint/MixedRegexpCaptureTypes: # (new in 0.85)
  Enabled: true

Lint/OutOfRangeRegexpRef: # (new in 0.89)
  Enabled: true

Lint/RaiseException: # (new in 0.81)
  Enabled: true

Lint/SelfAssignment: # (new in 0.89)
  Enabled: true

Lint/StructNewOverride: # (new in 0.81)
  Enabled: true

Lint/TopLevelReturnWithArgument: # (new in 0.89)
  Enabled: true

Lint/UnreachableLoop: # (new in 0.89)
  Enabled: true

Naming/RescuedExceptionsVariableName:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'hailstorm-gem/features/**/*'
    - 'hailstorm-cli/features/**/*'

Layout/EmptyLinesAroundAttributeAccessor: # (new in 0.83)
  Enabled: true

Layout/SpaceAroundMethodCallOperator: # (new in 0.82)
  Enabled: true

Layout/EmptyLines:
  Exclude:
    - 'hailstorm-gem/features/step_definitions/**/*_steps.rb'
    - 'hailstorm-cli/features/step_definitions/**/*_steps.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/Not:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/Alias:
  Enabled: false

Style/AccessorGrouping: # (new in 0.87)
  Enabled: true

Style/ArrayCoercion: # (new in 0.88)
  Enabled: true

Style/BisectedAttrAccessor: # (new in 0.87)
  Enabled: true

Style/CaseLikeIf: # (new in 0.88)
  Enabled: true

Style/ExplicitBlockArgument: # (new in 0.89)
  Enabled: true

Style/ExponentialNotation: # (new in 0.82)
  Enabled: true

Style/GlobalStdStream: # (new in 0.89)
  Enabled: true

Style/HashAsLastArrayItem: # (new in 0.88)
  Enabled: true

Style/HashEachMethods: # (new in 0.80)
  Enabled: true

Style/HashLikeCase: # (new in 0.88)
  Enabled: true

Style/HashTransformKeys: # (new in 0.80)
  Enabled: true

Style/HashTransformValues: # (new in 0.80)
  Enabled: true

Style/OptionalBooleanParameter: # (new in 0.89)
  Enabled: true

Style/RedundantAssignment: # (new in 0.87)
  Enabled: true

Style/RedundantFetchBlock: # (new in 0.86)
  Enabled: true

Style/RedundantFileExtensionInRequire: # (new in 0.88)
  Enabled: true

Style/RedundantRegexpCharacterClass: # (new in 0.85)
  Enabled: true

Style/RedundantRegexpEscape: # (new in 0.85)
  Enabled: true

Style/SingleArgumentDig: # (new in 0.89)
  Enabled: true

Style/SlicingWithRange: # (new in 0.83)
  Enabled: true

Style/StringConcatenation: # (new in 0.89)
  Enabled: true

Metrics/AbcSize:
  Max: 26

Metrics/MethodLength:
  Max: 25
  CountAsOne: ['array', 'hash', 'heredoc']

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - 'hailstorm-gem/spec/**/*'
    - 'hailstorm-gem/Rakefile'
    - 'hailstorm-gem/features/**/*'
    - 'hailstorm-cli/spec/**/*'
    - 'hailstorm-cli/Rakefile'
    - 'hailstorm-cli/features/**/*'
    - 'hailstorm-api/spec/**/*'
    - '**/*.gemspec'

Security/YAMLLoad:
  Enabled: false # safe_load is not as versatile as load
