# Top level rules
AllCops:
  Exclude:
    - '*.rb'
    - 'Vagrantfile'
    - 'docs/**/*'
    - 'hailstorm-gem/Gemfile'
    - 'hailstorm-gem/hailstorm.gemspec'
    - 'hailstorm-gem/Rakefile'
    - 'hailstorm-gem/bin/**/*'
    - 'hailstorm-gem/features/**/*'
    - 'hailstorm-gem/spec/**/*'
    - 'hailstorm-gem/templates/**/*'
    - 'hailstorm-gem/tmp/**/*'
    - 'hailstorm-redis/**/*'
    - 'hailstorm-site/**/*'
    - 'hailstorm-web/**/*'

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Lint/RescueException:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 15


