# Travis Configuration
sudo: enabled
dist: trusty

services:
  - mysql

language: ruby
rvm:
  - jruby-9.1.9.0
jdk:
  - oraclejdk8
cahce: bundler

install: bundle install
gemfile: hailstorm-gem/Gemfile
script:
  - cd hailstorm-gem && HAILSTORM_COVERAGE="true" JRUBY_OPTS="--debug" rspec

before_script:
  - mysql -e 'grant all privileges on *.* to "hailstorm_dev"@"localhost" identified by "hailstorm_dev";'
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - cd hailstorm-gem && ../cc-test-reporter format-coverage --add-prefix "hailstorm-gem" && ../cc-test-reporter upload-coverage

env:
  global:
    - CC_TEST_REPORTER_ID=3e42f82fe2b2f0601cafe4eca93a8c9d296dfa8f7af67d2e846a182a834bde59
