# Travis Configuration
sudo: enabled
dist: trusty

services:
  - mysql

language: ruby
rvm:
  - jruby-9.1.9.0
jdk:
  - oraclejdk8

cache: bundler

install: bundle install

gemfile:
  - hailstorm-gem/Gemfile
  - hailstorm-cli/Gemfile

before_install:
  - curl https://s3.amazonaws.com/aws-cli/awscli-bundle.zip -o awscli-bundle.zip
  - unzip awscli-bundle.zip
  - ./awscli-bundle/install -b ~/bin/aws
  - export PATH=~/bin:$PATH

script:
  - ./travis.sh -s

before_script:
  - ./travis.sh -b

after_script:
  - ./travis.sh -a

env:
  global:
    - AWS_DEFAULT_REGION=us-east-1
    - CC_TEST_REPORTER_ID=3e42f82fe2b2f0601cafe4eca93a8c9d296dfa8f7af67d2e846a182a834bde59
    - CI_NODE_TOTAL=2
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1

matrix:
  exclude:
  - gemfile: hailstorm-gem/Gemfile
    env: CI_NODE_INDEX=1
  - gemfile: hailstorm-cli/Gemfile
    env: CI_NODE_INDEX=0
