# Travis Configuration
sudo: enabled
dist: trusty

services:
  - mysql

language: ruby
rvm:
  - jruby-9.1.9.0
jdk:
  - oraclejdk8

install: bundle install
gemfile: hailstorm-gem/Gemfile
script:
  - ./run-travis-build.sh

before_script:
  - mysql -e 'grant all privileges on *.* to "hailstorm_dev"@"localhost" identified by "hailstorm_dev";'
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
