# Travis Configuration
services:
  - mysql

env:
  global:
    - AWS_DEFAULT_REGION=us-east-1
    - CC_TEST_REPORTER_ID=3e42f82fe2b2f0601cafe4eca93a8c9d296dfa8f7af67d2e846a182a834bde59
    - CI_NODE_TOTAL=6

stages:
  - name: test
    # if: branch != master AND (NOT(branch = develop AND type = push))
    if: branch = story/*
  - name: coverage
    # if: branch = develop AND type = push
    if: branch = develop

jobs:
  include:
    # ------------ TEST STAGE ----------------------
    - stage: test
      name: "hailstorm-gem test"
      language: ruby
      rvm: jruby-9.1.9.0
      jdk: openjdk8
      before_install:
        - make install_aws
      install:
        - make PROJECT=gem install
      script:
        - make PROJECT=gem test

    - stage: test
      name: "hailstorm-cli test"
      language: ruby
      rvm: jruby-9.1.9.0
      jdk: openjdk8
      before_install:
        - make install_aws
      install:
        - make PROJECT=cli install
      script:
        - make PROJECT=cli test

    - stage: test
      name: "hailstorm-api test"
      language: ruby
      rvm: jruby-9.1.9.0
      jdk: openjdk8
      before_install:
        - make install_aws
      install:
        - make PROJECT=api install
      script:
        - make PROJECT=api test

    - stage: test
      name: "hailstorm-file-server test"
      language: java
      jdk: openjdk8
      before_install:
        - make install_aws
      install:
        - make PROJECT=file-server install
      script:
        - make PROJECT=file-server test

    - stage: test
      name: "hailstorm-client-exchange test"
      language: java
      jdk: openjdk8
      before_install:
        - make install_aws
      install:
        - make PROJECT=client-exchange install
      script:
        - make PROJECT=client-exchange test

    - stage: test
      name: "hailstorm-web-client test"
      language: node_js
      node_js: lts/dubnium
      before_install:
        - make install_aws
      install:
        - make PROJECT=web-client install
      script:
        - make PROJECT=web-client test


    # ------------ COVERAGE -----------------------------------
    - stage: coverage
      name: "hailstorm-gem coverage"
      language: ruby
      rvm: jruby-9.1.9.0
      jdk: openjdk8
      env:
        - CI_NODE_INDEX=0
      before_install:
        - make install_aws
      install:
        - make PROJECT=gem FORCE=yes install
      script:
        - make PROJECT=gem coverage
      after_script:
        - make PROJECT=gem cc_test_report

    - stage: coverage
      name: "hailstorm-cli coverage"
      language: ruby
      rvm: jruby-9.1.9.0
      jdk: openjdk8
      env:
        - CI_NODE_INDEX=1
      before_install:
        - make install_aws
      install:
        - make PROJECT=cli FORCE=yes install
      script:
        - make PROJECT=cli coverage
      after_script:
        - make PROJECT=cli cc_test_report

    - stage: coverage
      name: "hailstorm-api coverage"
      language: ruby
      rvm: jruby-9.1.9.0
      jdk: openjdk8
      env:
        - CI_NODE_INDEX=2
      before_install:
        - make install_aws
      install:
        - make PROJECT=api FORCE=yes install
      script:
        - make PROJECT=api coverage
      after_script:
        - make PROJECT=api cc_test_report

    - stage: coverage
      name: "hailstorm-file-server coverage"
      language: java
      jdk: openjdk8
      env:
        - CI_NODE_INDEX=3
      before_install:
        - make install_aws
      install:
        - make PROJECT=file-server FORCE=yes install
      script:
        - make PROJECT=file-server coverage
      after_script:
        - make PROJECT=file-server cc_test_report

    - stage: coverage
      name: "hailstorm-client-exchange coverage"
      language: java
      jdk: openjdk8
      env:
        - CI_NODE_INDEX=4
      before_install:
        - make install_aws
      install:
        - make PROJECT=client-exchange FORCE=yes install
      script:
        - make PROJECT=client-exchange coverage
      after_script:
        - make PROJECT=client-exchange cc_test_report

    - stage: coverage
      name: "hailstorm-web-client coverage"
      language: node_js
      node_js: lts/dubnium
      env:
        - CI_NODE_INDEX=5
      before_install:
        - make install_aws
      install:
        - make PROJECT=web-client FORCE=yes install
      script:
        - make PROJECT=web-client coverage
      after_script:
        - make PROJECT=web-client cc_test_report
