version: '3.2'
services:
  web:
    image: "hailstorm/web-client:1.0.0"
    ports:
      - "8080:80"
    networks:
      - dmz
    tty:
      true
    depends_on:
      - file-server
      - client-exchange
      - hailstorm-api

  hailstorm-api:
    image: "hailstorm/hailstorm-api:1.0.0"
    ports:
      - "4567:8080"
    environment:
      HAILSTORM_DATABASE_PASSWORD: hailstorm
      HAILSTORM_ENV: production
      REDIS_URL: redis://hailstorm-mq/
    networks:
      - dmz
      - hailstorm
    depends_on:
      - hailstorm-db
      - client-exchange
    volumes:
      - type: volume
        source: hailstorm-home
        target: /home

  file-server:
    image: "hailstorm/hailstorm-file-server:1.0.0"
    hostname: "file-server"
    ports:
      - "9000:8080"
    networks:
      - dmz
    volumes:
      - type: volume
        source: hailstorm-file-store
        target: /hailstorm

  hailstorm-db:
    image: "mysql:5"
    hostname: "hailstorm-db"
    ports:
      - "3306:3306"
    networks:
      - hailstorm
    volumes:
      - type: volume
        source: hailstorm-db
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  hailstorm-mq:
    image: "redis:5.0.7-alpine"
    hostname: "hailstorm-mq"
    ports:
      - "6379:6379"
    networks:
      - hailstorm

  client-exchange:
    image: "hailstorm/hailstorm-client-exchange:1.0.0"
    hostname: "hailstorm-client-exchange"
    ports:
      - "9100:8080"
    networks:
      - hailstorm
      - dmz
    depends_on:
      - hailstorm-mq
    entrypoint:
      - "java"
      - "-jar"
      - "/app.jar"
      - "--redisHost=hailstorm-mq"

networks:
  dmz:
  hailstorm:

volumes:
  hailstorm-file-store:
  hailstorm-db:
  hailstorm-home:
