version: '3.2'
services:
  web:
    image: "hailstorm/web-client"
    ports:
      - "8080:80"
    networks:
      - dmz
    tty:
      true
    depends_on:
      - file-server

  file-server:
    image: "hailstorm/hailstorm-file-server"
    hostname: "hailstorm-file-server"
    ports:
      - "9000:8080"
    networks:
      - dmz
    volumes:
      - type: volume
        source: fileStore
        target: /hailstorm
  
  hailstorm-db:
    image: "mysql:5"
    hostname: "hailstorm-db"
    ports:
      - "3306:3306"
    networks:
      - hailstorm
    volumes:
      - type: volume
        source: hailstorm-db-vol
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'i r baboon'

networks:
  dmz:
  hailstorm:

volumes:
  fileStore:
  hailstorm-db-vol:
