version: '3.2'
services:
  hailstorm-db:
    image: "mysql:5"
    hostname: "hailstorm-db"
    ports:
      - "3306:3306"
    networks:
      - hailstorm
    volumes:
      - type: volume
        source: hailstorm-db
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

networks:
  hailstorm:

volumes:
  hailstorm-db:
